language: go
go:
    - "1.10"
    - "1.11"
go_import_path: github.com/deadcheat/goblet
before_install:
    - go get -v -u github.com/modocache/gover
    - go get -v -u github.com/mattn/goveralls
    - go get -v -u golang.org/x/tools/cmd/cover
install: true
script:
    - env GO111MODULE=on go build
    - env GO111MODULE=on go test -coverprofile=goblet.coverprofile github.com/deadcheat/goblet
    - env GO111MODULE=on go test -coverprofile=goblet-presenter.coverprofile github.com/deadcheat/goblet/generator/presenter/file
    - env GO111MODULE=on go test -coverprofile=goblet-repository.dotfileignore.coverprofile github.com/deadcheat/goblet/generator/repository/dotfileignorematcher
    - env GO111MODULE=on go test -coverprofile=goblet-repository.regexpmatcher.coverprofile github.com/deadcheat/goblet/generator/repository/regexpmatcher
    - env GO111MODULE=on go test -coverprofile=goblet-usecase.coverprofile github.com/deadcheat/goblet/generator/usecase/file
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
