language: go
go:
    - "1.10"
go_import_path: github.com/deadcheat/goblet
before_install:
    - go get -v -u github.com/modocache/gover
    - go get -v -u github.com/mattn/goveralls
    - go get -v -u golang.org/x/tools/cmd/cover
    - go get -v -u github.com/Masterminds/glide
install:
    - $GOPATH/bin/glide install
script:
    - go test -coverprofile=goblet.coverprofile github.com/deadcheat/goblet
    - go test -coverprofile=goblet-presenter.coverprofile github.com/deadcheat/goblet/generator/presenter/file
    - go test -coverprofile=goblet-repository.coverprofile github.com/deadcheat/goblet/generator/repository/regexp
    - go test -coverprofile=goblet-usecase.coverprofile github.com/deadcheat/goblet/generator/usecase/file
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
